[package]
name = "alkyd"
version = "0.1.18"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "bevy crate for handling procedural textures and shaders"
exclude = ["src/bin"]

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.24.0"
bevy_app_compute = { path = "./crates/bevy_app_compute" }

[dependencies.bitflags]
version = "2.5.0"

[lib]
name = "alkyd"
path = "src/lib.rs"

[dev-dependencies]
bevy = { version = "0.13.2", features = ["trace", "trace_tracy_memory"] }


# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
codegen-units = 1
