[package]
name = "alkyd"
version = "0.1.22"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "bevy crate for handling procedural textures and shaders"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.24.0"
bevy_embedded_assets = "0.10.2"
parking_lot = "0.12.1"
bytemuck = "1.16.0"
wgpu = { version = "0.19.1", features = ["naga"] }
naga = { version = "0.19.0", features = ["wgsl-in"] }
naga_oil = { version = "0.13,0", default-features = false, features = [
    "test_shader",
] }

[dependencies.bitflags]
version = "2.5.0"

[lib]
name = "alkyd"
path = "src/lib.rs"

[dev-dependencies]
bevy = { version = "0.13.2", features = ["trace", "trace_tracy_memory"] }

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
codegen-units = 1
