[package]
name = "alkyd"
version = "0.1.29"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "bevy crate for handling procedural textures and shaders"
exclude = ["src/bin"]

[dependencies]
bevy = "0.13.2"
bevy-inspector-egui = { git = "https://github.com/jakobhellermann/bevy-inspector-egui/", branch = "main" }
parking_lot = "0.12.1"
bytemuck = "1.16.0"
wgpu = { version = "0.19.1", features = ["naga"] }
naga = { version = "0.19.0", features = ["wgsl-in"] }
naga_oil = { version = "0.13,0", default-features = false, features = [
    "test_shader",
] }

[dependencies.bitflags]
version = "2.5.0"


[lib]
name = "alkyd"
path = "src/lib.rs"

[dev-dependencies]
bevy = "0.13.2"

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
codegen-units = 1
opt-level = "z"
strip = true
lto = true
