[package]
name = "alkyd"
version = "0.1.40"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "bevy crate for handling procedural textures and shaders"
publish = true

[dependencies]
bevy = { version = "0.14.1", default-features = false, features = [
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_asset",
    "png",
] }
rand = { version = "0.8", optional = true }
rand_pcg = { version = "0.3", optional = true }
serde = { version = "1.0", features = ["derive"] }
anyhow = { version = "1.0", optional = true }
ron = { version = "0.7", optional = true }
bytemuck = { version = "1.2.0-alpha.1", optional = true }
cfg-if = "1.0.0"
bevy_mod_picking = { version = "0.20.1", optional = true }
bevy_panorbit_camera = { version = "0.19.1" }
crevice = { version = "0.16.0", optional = true }
sickle_ui = { version = "0.2.1", optional = true }

[dependencies.bitflags]
version = "2.5.0"

[dev-dependencies]
bevy = { version = "0.14.1", default-features = false, features = [
    "bevy_winit",
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_pbr",
    "wgpu_trace",
    "bevy_asset",
    "png",
] }
bytemuck = "1.5"
rand = "0.8"
rand_pcg = "0.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
ron = "0.7"
cfg-if = "1.0.0"
crevice = { version = "0.16.0" }
sickle_ui = { version = "0.2.1"}

[features]
editor = [
    "dep:sickle_ui",
    "dep:rand_pcg",
    "dep:rand",
    "dep:bytemuck",
    "compute",
]
compute = ["dep:crevice"]
default = []

[lib]
name = "alkyd"
path = "src/lib.rs"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
