[package]
name = "alkyd"
version = "0.1.35"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "bevy crate for handling procedural textures and shaders"
publish = true

[dependencies]
bevy = { version = "0.14.0", features = [
    "wgpu_trace",
    "bevy_debug_stepping",
    "bevy_dev_tools",
] }
rand = "0.8"
rand_pcg = "0.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
ron = "0.7"
bytemuck = "1.2.0-alpha.1"
bevy_quill = { version = "0.1.2", optional = true }
bevy_quill_obsidian = { version = "0.1.0", optional = true }
bevy_quill_obsidian_inspect = { version = "0.1.0", optional = true }
bevy_mod_stylebuilder = { version = "0.1.1", optional = true }
bevy_mod_picking = { version = "0.20.1", optional = true }
bevy_panorbit_camera = { version = "0.19.1", optional = true }
cfg-if = "1.0.0"

[dependencies.bitflags]
version = "2.5.0"

[dev-dependencies]
bevy = { version = "0.14.0", default-features = false, features = [
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_asset",
    "png",
] }
bytemuck = "1.5"
rand = "0.8"
rand_pcg = "0.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
ron = "0.7"

[target.'cfg(debug)'.build-dependencies]
bevy = { version = "0.14.0", default-features = false, features = [
    "bevy_debug_stepping",
    "bevy_dev_tools",
    "bevy_ci_testing",
] }
rand = "0.8"
rand_pcg = "0.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
ron = "0.7"
cfg-if = "1.0.0"
bytemuck = "1.2.0-alpha.1"
bevy_quill = { version = "0.1.2", optional = true }
bevy_quill_obsidian = { version = "0.1.0", optional = true }
bevy_quill_obsidian_inspect = { version = "0.1.0", optional = true }
bevy_mod_stylebuilder = { version = "0.1.1", optional = true }
bevy_mod_picking = { version = "0.20.1", optional = true }
bevy_panorbit_camera = { version = "0.19.1", optional = true }


[features]
editor = [
    "dep:bevy_quill",
    "dep:bevy_quill_obsidian",
    "dep:bevy_mod_stylebuilder",
    "dep:bevy_mod_picking",
    "dep:bevy_panorbit_camera",
]

[lib]
name = "alkyd"
path = "src/lib.rs"

[profile.dev]
debug = true
