[package]
name = "alkyd"
version = "0.1.31"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "bevy crate for handling procedural textures and shaders"
publish = true

[dependencies]
naga_oil = { version = "0.14.*", default-features = false }
bevy = { workspace = true, default-features = false, features = [
    "bevy_asset",         # Assets management
    "bevy_scene",         # Scenes management
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_winit",         # Window management (cross-platform Winit backend)
    "bevy_pbr",
    "tonemapping_luts",
] }
bytemuck.workspace = true
bevy-inspector-egui.workspace = true
bevy_third_person_camera.workspace = true
wgpu = { version = "0.20.1", features = ["naga"] }
naga = { version = "0.20.0", features = ["wgsl-in"] }
parking_lot = "0.12.3"

[dependencies.bitflags]
version = "2.5.0"

[lib]
name = "alkyd"
path = "src/lib.rs"
