[package]
name = "alkyd"
version = "0.1.32"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "bevy crate for handling procedural textures and shaders"
publish = true

[dependencies]
bevy = { workspace = true}
bevy-inspector-egui.workspace = true
bytemuck.workspace = true
parking_lot = "0.12.1"
futures-lite = "1.13.0"
naga = { version = "0.20.0", features = ["wgsl-in"] }
wgpu = { version = "0.20.1", features = ["naga"] }
naga_oil = { version = "0.14.0"}
bevy_third_person_camera.workspace = true
cc = "1.0.73"

[dependencies.bitflags]
version = "2.5.0"

[dev-dependencies]

[lib]
name = "alkyd"
path = "src/lib.rs"
