[dependencies]
bevy = "0.13.2"
bevy-inspector-egui = "0.24.0"
bevy_third_person_camera = { path = "../../../crates/bevy_third_person_camera" }

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
codegen-units = 1
