name: CD

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION_STABLE: 1.85.0
  CRATE_PATHS: .
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION_STABLE }}
          profile: minimal
          override: true
      - name: Publish
        run: bash .github/workflows/scripts/run_publication.sh
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_TOKEN }}

 